---

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

  # RVM Install
- name: check for mpapis gpg key
  shell: gpg --list-keys mpapis
  become: false
  register: mpapis_gpg_key_exists
  ignore_errors: true

- name: import GPG key
  shell: "curl -sSL https://rvm.io/mpapis.asc | gpg --import -"
  become: false
  when: mpapis_gpg_key_exists is defined and mpapis_gpg_key_exists.rc is defined and mpapis_gpg_key_exists.rc != 0 

- name: download RVM
  get_url:
    url: "{{rvm.url}}"
    dest: "{{rvm.temp_installer_path}}"

- name: set executable
  file:
    path: "{{rvm.temp_installer_path}}"
    mode: 0755

- name: installing RVM 
  become: false
  command: "{{rvm.temp_installer_path}} --path {{rvm.root}} stable"

- name: setting RVM autolibs
  become: false
  command: "{{rvm.root}}/bin/rvm autolibs 3"

  # Ruby Install
- name: installing Ruby
  become: false
  command: "{{rvm.root}}/bin/rvm install {{rvm.default_ruby_version}}"

- name: setting default Ruby
  shell: "source {{rvm.init_script}} && rvm use {{rvm.default_ruby_version}} --default executable=/bin/bash"
  become: false
  register: rvm_select_ruby_version_root
  ignore_errors: True
  changed_when: False
