
- name: install warvox deps
  apt: "name={{ item }} state=installed"
  with_items:
    - gnuplot 
    - lame 
    - build-essential 
    - libssl-dev 
    - libcurl4-openssl-dev
    - postgresql 
    - postgresql-contrib 
    - postgresql-common 
    - git-core 
    - curl 
    - libpq-dev
    - sox
